/gps/particle neutron
/gps/ang/type iso
/gps/energy 14.08 MeV
/benchmark/material/setRegionMaterial Li7
/benchmark/material/setRegionAtomicNumber 3. mm
/benchmark/material/setRegionNucleonNumber 7. mm
/benchmark/material/setRegionAtomicMass 7.0160 mm
#/scoring/energy_bins "vitamin-j 175"
#/scoring/tallies/vol "phys1 vitamin-j"
/run/initialize
/run/setCutForAGivenParticle e- 10. cm
/run/setCutForAGivenParticle gamma 30. cm
/run/setCutForAGivenParticle proton 30. cm
/run/printProgress 10000
/run/beamOn 100000