/gps/particle neutron
/gps/ang/type iso
/gps/energy 14.08 MeV
/benchmark/material/setRegionMaterial Fe56
/benchmark/material/setRegionAtomicNumber 26. mm
/benchmark/material/setRegionNucleonNumber 56. mm
/benchmark/material/setRegionAtomicMass 55.9349375 mm
#/scoring/energy_bins "vitamin-j 175"
#/scoring/tallies/vol "phys1 vitamin-j"
/run/initialize
/run/setCutForAGivenParticle e- 10. cm
/run/setCutForAGivenParticle gamma 30. cm
/run/setCutForAGivenParticle proton 30. cm
/run/printProgress 10000
/run/beamOn 100000